package config

import (
	"path/filepath"
	"strings"

	"github.com/davidbelicza/semantic-search/internal/textproc"
)

// The guard skips files carrying a config extension that are not hand-written settings: lock
// files and tool output. They are large and machine-written, and would bury the real config.

const generatedScanLines = 8

var lockFileNames = []string{
	"package-lock.json",
	"npm-shrinkwrap.json",
	"installed.json",
	"composer.lock.json",
	"bun.lock",
	"deno.lock",
}

var generatedNameFragments = []string{".min.", "-lock.", ".generated.", ".g."}

var generatedMarkers = []string{"do not edit", "code generated", "auto-generated", "autogenerated", "@generated"}

func hasExcludedName(path string) bool {
	name := strings.ToLower(filepath.Base(path))

	return isLockFileName(name) || hasGeneratedNameFragment(name)
}

func isLockFileName(name string) bool {
	for _, lock := range lockFileNames {
		if name == lock {
			return true
		}
	}

	return false
}

func hasGeneratedNameFragment(name string) bool {
	for _, fragment := range generatedNameFragments {
		if strings.Contains(name, fragment) {
			return true
		}
	}

	return false
}

func isGeneratedContent(source string) bool {
	lines := textproc.NonEmptyLines(source)
	if len(lines) > generatedScanLines {
		lines = lines[:generatedScanLines]
	}

	return anyLineHasMarker(lines)
}

func anyLineHasMarker(lines []string) bool {
	for _, line := range lines {
		if hasGeneratedMarker(strings.ToLower(line)) {
			return true
		}
	}

	return false
}

func hasGeneratedMarker(line string) bool {
	for _, marker := range generatedMarkers {
		if strings.Contains(line, marker) {
			return true
		}
	}

	return false
}
