package config

import (
	"strings"
	"testing"
)

func TestIsGeneratedContentOnlyScansTheLeadingLines(t *testing.T) {
	var lines []string
	for i := 0; i < 12; i++ {
		lines = append(lines, "key = value")
	}
	lines = append(lines, "# code generated by tool")

	if isGeneratedContent(strings.Join(lines, "\n")) {
		t.Fatal("a marker past the scan window should not count")
	}
	if !isGeneratedContent("# @generated\nkey = value") {
		t.Fatal("a marker in the leading lines should count")
	}
}

func TestConfigDropsGeneratedContent(t *testing.T) {
	parsed, err := newConfig().Parse([]byte("# Code generated by tool. DO NOT EDIT.\nkey = value\n"))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(parsed.Sections) != 0 {
		t.Fatalf("want no sections for generated content, got %d", len(parsed.Sections))
	}
}

func TestConfigSkipsLockFilesAndGeneratedNames(t *testing.T) {
	s := newConfig()
	for _, path := range []string{"/p/package-lock.json", "/p/npm-shrinkwrap.json", "/p/app.min.json", "/p/deps-lock.yaml"} {
		if s.Claims(path) {
			t.Fatalf("should not claim %q", path)
		}
	}
}

func TestConfigSkipsComposerInstalledManifest(t *testing.T) {
	if newConfig().Claims("/p/vendor/composer/installed.json") {
		t.Fatal("installed.json is generated by composer and should be skipped")
	}
}
