package config

import (
	"strings"
	"testing"

	"github.com/davidbelicza/semantic-search/core/storage"
	"github.com/davidbelicza/semantic-search/core/strategy"
	"github.com/davidbelicza/semantic-search/core/strategy/general"
)

func newConfig() strategy.Strategy {
	return NewConfigStrategy(general.NewGeneralStrategy(nil, nil))
}

// chunksOf runs the whole per-file recipe for a source, which is where the format parser is
// chosen: Parse carries the text, Chunk structures it.
func chunksOf(t *testing.T, path, source string) []storage.Chunk {
	t.Helper()

	parsed, err := newConfig().Parse([]byte(source))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	chunks, err := newConfig().Chunk(storage.Document{AbsolutePath: path}, parsed)
	if err != nil {
		t.Fatalf("chunk: %v", err)
	}

	return chunks
}

func joinedText(chunks []storage.Chunk) string {
	var out strings.Builder
	for _, chunk := range chunks {
		out.WriteString(chunk.Title + "\n" + chunk.Text + "\n")
	}

	return out.String()
}

func TestConfigClaimsOnlyConfigExtensions(t *testing.T) {
	s := newConfig()
	for _, path := range []string{"a.json", "a.xml", "a.yaml", "a.yml", "a.ini", "a.properties", "A.JSON", "A.Yml"} {
		if !s.Claims(path) {
			t.Fatalf("should claim %q", path)
		}
	}
	for _, path := range []string{"a.md", "a.txt", "a.go", "a.html", "a.docx", "noext"} {
		if s.Claims(path) {
			t.Fatalf("should not claim %q", path)
		}
	}
}

// .xhtml belongs to the HTML strategy. filepath.Ext returns the segment after the last dot, so
// the two extensions are distinct keys and the strategies can never contend for a file.
func TestConfigNeverClaimsXHTML(t *testing.T) {
	s := newConfig()
	for _, path := range []string{"a.xhtml", "a.XHTML", "page.rss.xhtml"} {
		if s.Claims(path) {
			t.Fatalf("should not claim %q, it is the HTML strategy's", path)
		}
	}
	if !s.Claims("feed.rss.xml") {
		t.Fatal("should claim a multi-dot .xml file")
	}
}

// TOML is deliberately not in the set; it is deferred rather than half-supported through the
// INI parser, which would produce silently wrong paths for arrays of tables.
func TestConfigDoesNotClaimTOML(t *testing.T) {
	if newConfig().Claims("Cargo.toml") {
		t.Fatal("should not claim .toml")
	}
}

func TestConfigSkipsLockFilesAndGeneratedNames(t *testing.T) {
	s := newConfig()
	for _, path := range []string{"/p/package-lock.json", "/p/npm-shrinkwrap.json", "/p/app.min.json", "/p/deps-lock.yaml"} {
		if s.Claims(path) {
			t.Fatalf("should not claim %q", path)
		}
	}
}

func TestConfigDropsGeneratedContent(t *testing.T) {
	parsed, err := newConfig().Parse([]byte("# Code generated by tool. DO NOT EDIT.\nkey = value\n"))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(parsed.Sections) != 0 {
		t.Fatalf("want no sections for generated content, got %d", len(parsed.Sections))
	}
}

func TestConfigTitlesChunksByKeyPath(t *testing.T) {
	source := strings.Join([]string{
		"database:",
		"  primary:",
		"    host: " + strings.Repeat("d", 2000),
		"cache:",
		"  size: " + strings.Repeat("c", 600),
	}, "\n")

	chunks := chunksOf(t, "/p/app.yaml", source)

	joined := joinedText(chunks)
	if !strings.Contains(joined, "database > primary") {
		t.Fatalf("want a key-path title, got:\n%s", joined)
	}
	if !strings.Contains(joined, "cache") {
		t.Fatalf("want the cache section, got:\n%s", joined)
	}
}

func TestConfigFallsBackToTheFileTitleForRootSettings(t *testing.T) {
	chunks := chunksOf(t, "/p/settings.ini", "retries = 3\n")

	if len(chunks) != 1 {
		t.Fatalf("want one chunk, got %d", len(chunks))
	}
	if chunks[0].Title != "settings" {
		t.Fatalf("want the file title, got %q", chunks[0].Title)
	}
}

// Credentials are the reason config files are risky to index: the text is sent to the
// embedding endpoint and stored. The key stays searchable, the value does not travel.
func TestConfigRedactsCredentialValues(t *testing.T) {
	source := strings.Join([]string{
		"db:",
		"  user: appuser",
		"  password: hunter2",
		"  api_key: sk-live-9f3c",
		"  auth_token: t0ps3cret",
	}, "\n")

	joined := joinedText(chunksOf(t, "/p/app.yaml", source))

	for _, secret := range []string{"hunter2", "sk-live-9f3c", "t0ps3cret"} {
		if strings.Contains(joined, secret) {
			t.Fatalf("secret %q reached the index:\n%s", secret, joined)
		}
	}
	for _, key := range []string{"password", "api_key", "auth_token"} {
		if !strings.Contains(joined, key) {
			t.Fatalf("key %q should stay searchable:\n%s", key, joined)
		}
	}
	if !strings.Contains(joined, "user = appuser") {
		t.Fatalf("ordinary settings should be untouched:\n%s", joined)
	}
}

// A config with a syntax error is still worth finding, so it degrades to text rather than
// failing the file.
func TestConfigFallsBackToTextWhenTheSourceDoesNotParse(t *testing.T) {
	chunks := chunksOf(t, "/p/broken.json", `{"host": "db01", `)

	if len(chunks) == 0 {
		t.Fatal("want the file indexed as text")
	}
	if !strings.Contains(joinedText(chunks), "db01") {
		t.Fatalf("want the raw text kept, got:\n%s", joinedText(chunks))
	}
}

func TestConfigChunkReturnsNothingForAnEmptyDocument(t *testing.T) {
	chunks, err := newConfig().Chunk(storage.Document{AbsolutePath: "/p/a.json"}, strategy.ParsedDocument{})
	if err != nil {
		t.Fatalf("chunk: %v", err)
	}
	if len(chunks) != 0 {
		t.Fatalf("want no chunks, got %d", len(chunks))
	}
}

func TestConfigIndexesEveryFormatItClaims(t *testing.T) {
	cases := []struct{ path, source, want string }{
		{"/p/a.json", `{"port":8080}`, "port = 8080"},
		{"/p/a.xml", `<cfg><port>8080</port></cfg>`, "port = 8080"},
		{"/p/a.yaml", "port: 8080", "port = 8080"},
		{"/p/a.ini", "[server]\nport = 8080", "port = 8080"},
		{"/p/a.properties", "server.port=8080", "port = 8080"},
	}

	for _, testCase := range cases {
		joined := joinedText(chunksOf(t, testCase.path, testCase.source))
		if !strings.Contains(joined, testCase.want) {
			t.Fatalf("%s: want %q in:\n%s", testCase.path, testCase.want, joined)
		}
	}
}

// The formats converge on one rendering so a query behaves the same whatever the source was.
func TestConfigRendersEveryFormatTheSameWay(t *testing.T) {
	sources := map[string]string{
		"/p/a.json": `{"server":{"port":8080}}`,
		"/p/a.yaml": "server:\n  port: 8080",
		"/p/a.xml":  "<server><port>8080</port></server>",
		"/p/a.ini":  "[server]\nport = 8080",
	}

	for path, source := range sources {
		chunks := chunksOf(t, path, source)
		if len(chunks) != 1 {
			t.Fatalf("%s: want one chunk, got %d", path, len(chunks))
		}
		if !strings.Contains(chunks[0].Text, "port = 8080") {
			t.Fatalf("%s: rendered differently: %q", path, chunks[0].Text)
		}
	}
}
