package code

import (
	"path/filepath"
	"strings"
)

// The guard skips files that carry a code extension but are not human-authored source we want
// in the index: minified bundles and generated output. They embed as noise and pollute
// search, so they are filtered out entirely (no sections, hence no chunks).

const (
	// maxLineRunes flags minified files: a single line far longer than any hand-written line
	// of code is the reliable signature of a bundle.
	maxLineRunes = 5000
	// generatedScanLines bounds how far down the file we look for a generated-code banner.
	generatedScanLines = 8
)

// minifiedNameFragments are name markers of pre-built or minified artifacts.
var minifiedNameFragments = []string{".min.", "-min.", ".bundle."}

// generatedMarkers are banners tools emit at the top of generated files.
var generatedMarkers = []string{"do not edit", "code generated", "auto-generated", "autogenerated", "@generated"}

// isExcludedContent reports whether already-read content should be excluded from indexing.
// The name-based check lives in Claims (which has the path); this is the content half.
func isExcludedContent(source string) bool {
	return isMinifiedContent(source) || isGenerated(source)
}

func hasMinifiedName(path string) bool {
	name := strings.ToLower(filepath.Base(path))
	for _, fragment := range minifiedNameFragments {
		if strings.Contains(name, fragment) {
			return true
		}
	}

	return false
}

func isMinifiedContent(source string) bool {
	for _, line := range strings.Split(source, "\n") {
		if len([]rune(line)) > maxLineRunes {
			return true
		}
	}

	return false
}

func isGenerated(source string) bool {
	lines := strings.Split(source, "\n")
	for i, line := range lines {
		if i >= generatedScanLines {
			return false
		}
		if lineHasGeneratedMarker(line) {
			return true
		}
	}

	return false
}

func lineHasGeneratedMarker(line string) bool {
	lower := strings.ToLower(line)
	for _, marker := range generatedMarkers {
		if strings.Contains(lower, marker) {
			return true
		}
	}

	return false
}
