package code

import (
	"strings"
	"testing"

	"github.com/davidbelicza/semantic-search/core/storage"
	"github.com/davidbelicza/semantic-search/core/strategy"
	"github.com/davidbelicza/semantic-search/core/strategy/general"
)

func newCode() strategy.Strategy {
	return NewCodeStrategy(general.NewGeneralStrategy(nil, nil))
}

// sectionsOf runs the strategy's language split for a given path, returning the structured
// sections so tests can assert boundaries and nesting paths.
func sectionsOf(t *testing.T, path, source string) []strategy.Section {
	t.Helper()
	s := NewCodeStrategy(general.NewGeneralStrategy(nil, nil)).(codeStrategy)
	return s.splitSource(path, source)
}

func TestCodeClaimsWhitelistAndSkipsMinifiedNames(t *testing.T) {
	s := newCode()
	for _, path := range []string{"a.go", "a.py", "a.php", "a.ts", "a.rb", "a.sql", "A.GO"} {
		if !s.Claims(path) {
			t.Fatalf("should claim %q", path)
		}
	}
	for _, path := range []string{"a.md", "a.pdf", "a.txt", "noext", "app.min.js", "vendor.bundle.js"} {
		if s.Claims(path) {
			t.Fatalf("should not claim %q", path)
		}
	}
}

func TestBracePHPMethodsGetClassPath(t *testing.T) {
	source := strings.Join([]string{
		"<?php",
		"namespace App;",
		"",
		"class Invoice",
		"{",
		"    public readonly array $lines;",
		"",
		"    /** Sum of all line items. */",
		"    public function total(): float",
		"    {",
		`        return array_sum($this->lines); // "{" in a string`,
		"    }",
		"}",
	}, "\n")

	sections := sectionsOf(t, "invoice.php", source)

	total := findSection(t, sections, []string{"class Invoice", "total()"})
	if !strings.Contains(total.Body, "public function total(): float") {
		t.Fatalf("method body missing signature: %q", total.Body)
	}
	if !strings.Contains(total.Body, "Sum of all line items") {
		t.Fatalf("doc-comment should attach to the method: %q", total.Body)
	}
}

func TestBraceDoesNotMistakeCallsForDefinitions(t *testing.T) {
	source := strings.Join([]string{
		"<?php",
		"function run(): void",
		"{",
		"    doWork();",
		"    $this->total();",
		"}",
	}, "\n")

	sections := sectionsOf(t, "run.php", source)

	paths := allPaths(sections)
	if got := countFuncSections(sections); got != 1 {
		t.Fatalf("want exactly one function section, got %d (%v)", got, paths)
	}
	findSection(t, sections, []string{"run()"})
}

func TestIndentPythonMethodsGetClassPath(t *testing.T) {
	source := strings.Join([]string{
		"import math",
		"",
		"class Invoice:",
		"    \"\"\"An invoice.\"\"\"",
		"    def total(self) -> float:",
		"        return sum(self.lines)",
		"",
		"    def tax(self) -> float:",
		"        return self.total() * 0.2",
		"",
		"def top_level():",
		"    return 1",
	}, "\n")

	sections := sectionsOf(t, "billing.py", source)

	findSection(t, sections, []string{"class Invoice", "total()"})
	findSection(t, sections, []string{"class Invoice", "tax()"})
	findSection(t, sections, []string{"top_level()"})
}

func TestFlatFamilyRubyProducesWholeFileSection(t *testing.T) {
	source := "def hello\n  puts 'hi'\nend\n"
	sections := sectionsOf(t, "a.rb", source)
	if len(sections) != 1 {
		t.Fatalf("flat family should yield one section, got %d", len(sections))
	}
	if len(sections[0].Path) != 0 {
		t.Fatalf("flat section should have no path, got %v", sections[0].Path)
	}
}

func TestParseDropsMinifiedContent(t *testing.T) {
	long := strings.Repeat("a=1;", 2000) // one very long line
	parsed, err := newCode().Parse([]byte("function f(){}\n" + long))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(parsed.Sections) != 0 {
		t.Fatalf("minified content should yield no sections, got %d", len(parsed.Sections))
	}
}

func TestParseDropsGeneratedContent(t *testing.T) {
	source := "// Code generated by protoc. DO NOT EDIT.\npackage p\nfunc F(){}\n"
	parsed, err := newCode().Parse([]byte(source))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(parsed.Sections) != 0 {
		t.Fatalf("generated content should yield no sections, got %d", len(parsed.Sections))
	}
}

func TestChunkTitlesCarryNestingPath(t *testing.T) {
	source := "<?php\nclass Invoice\n{\n    public function total(): float\n    {\n        return 1.0;\n    }\n}\n"
	s := newCode()
	parsed, err := s.Parse([]byte(source))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	chunks, err := s.Chunk(storage.Document{AbsolutePath: "invoice.php"}, parsed)
	if err != nil {
		t.Fatalf("chunk: %v", err)
	}
	if !hasTitle(chunks, "class Invoice > total()") {
		t.Fatalf("no chunk titled with the nesting path: %v", titles(chunks))
	}
}

// --- helpers ---

func findSection(t *testing.T, sections []strategy.Section, path []string) strategy.Section {
	t.Helper()
	for _, s := range sections {
		if equalPath(s.Path, path) {
			return s
		}
	}
	t.Fatalf("no section with path %v; got %v", path, allPaths(sections))
	return strategy.Section{}
}

func equalPath(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func allPaths(sections []strategy.Section) [][]string {
	paths := make([][]string, len(sections))
	for i, s := range sections {
		paths[i] = s.Path
	}
	return paths
}

func countFuncSections(sections []strategy.Section) int {
	count := 0
	for _, s := range sections {
		if len(s.Path) > 0 && strings.HasSuffix(s.Path[len(s.Path)-1], "()") {
			count++
		}
	}
	return count
}

func hasTitle(chunks []storage.Chunk, title string) bool {
	for _, c := range chunks {
		if c.Title == title {
			return true
		}
	}
	return false
}

func titles(chunks []storage.Chunk) []string {
	out := make([]string, len(chunks))
	for i, c := range chunks {
		out[i] = c.Title
	}
	return out
}
